# Generated by Django 5.1.1 on 2024-09-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Apprentice Software Engineer", "AP"),
                    ("Software Engineer", "SWE"),
                    ("Senior Software Engineer", "SR"),
                    ("Staff Software Engineer", "ST"),
                ],
                max_length=50,
            ),
        ),
    ]
