# Generated by Django 5.1.1 on 2024-09-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="image",
            new_name="profile_picture",
        ),
    ]
