# Generated by Django 5.1.1 on 2024-09-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_rename_image_customuser_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="profile_picture",
            new_name="image",
        ),
    ]
