# Generated by Django 5.1.1 on 2024-09-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_bank", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("AP", "Apprentice Software Engineer"),
                    ("SWE", "Software Engineer"),
                    ("SR", "Senior Software Engineer"),
                    ("ST", "Staff Software Engineer"),
                ],
                default="SWE",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="second_name",
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
