# Generated by Django 5.1.1 on 2024-09-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_bank", "0005_profile_first_name_profile_role_profile_second_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="second_name",
        ),
    ]
